### ISSUE TITLE
code organisation

### ISSUE THREAD

**Issue by mkborregaard** [EcoJulia/NeutralLandscapes.jl#25]
Do we really need small files for every algorithm? Or would NeutralLandscapes.jl, utils.jl and algorithms.jl be clearer?

**Comment by tpoisot** [comment]
I assumed that more algorithms would require their own helper functions, which has proven... untrue so far. That being said,  a file for each algorithm makes `Ctrl-P` very effective at navigating the repo. No strong opinion here.

**Comment by rafaqz** [comment]
Perlin noise is pretty big - it has multiple helper functions! But yes the other methods are a bit light on. It does make it easy to find formulations, which is nice. And we could probably fill out the docs a bit. 

We organise Dispersal.jl like this, except with a bit of clustering - similar algorithms can be in one file, like exponential/logistic growth are in growth.jl, and both are tested in test/growth.jl.
