### ISSUE TITLE
MethodError: no method matching NearestNeighborCluster(::Float64)

### ISSUE THREAD

**Issue by jesseseeem** [EcoJulia/NeutralLandscapes.jl#51]
**Describe the bug**
following error generated when I try to execute 
```julia
Fig1i = rand(NearestNeighborCluster(0.4), siz)

ERROR: MethodError: no method matching NearestNeighborCluster(::Float64)
```

**Environment:**
 - OS: MacOS 11.2.3 (20D91) (Big Sur)
 - Julia version: Version 1.5.4 (2021-03-11)
 - Other packages used in the example and their versions: using NeutralLandscapes, Plots

**Comment by mkborregaard** [comment]
Hi Jesse, good to see you using Julia and I didn't corrupt you totally with my R lessons :-)
As we've currently defined this the syntax is 
```julia
Fig1i = rand(NearestNeighborCluster(p = 0.4), siz)
```
because of the kwdef constructor. @tpoisot @rafaqz is that what we want?

**Comment by tpoisot** [comment]
Is `@kwdef` replacing the default constructor? I'll look into it.

**Comment by rafaqz** [comment]
Its because it has 2 arguments... Do we want the default values as trailing arguments as well? I should have kept both forms. Will PR.

**Comment by tpoisot** [comment]
Is this not creating some ambiguity though? Let's add a paragraph to the documentation explaining that the types use keywords?

**Comment by rafaqz** [comment]
I'm easy either way, but the PR is there to have both. I can gut it and just keep the testing of kw constructors if everyone thinks kw only is best.

But it turned out there were a few with arg defaults that I had missed earlier - we should probably have either one or both syntaxes for all algorithms to avoid confusion

**Comment by mkborregaard** [comment]
both sounds great
