### ISSUE TITLE
[RFC] adding methods for temporal change in neutral landscapes

### ISSUE THREAD

**Issue by gottacatchenall** [EcoJulia/NeutralLandscapes.jl#56]
As part of an ongoing project, I need a way to simulate species occurrence as a function of the environment, where the environment changes in a neutral way (see [this issue](https://github.com/EcoJulia/BiodiversityObservationNetworks.jl/issues/1#issuecomment-999744834)). I can imagine adding methods for various types of environmental change (whether is be directional change or random fluctuations around the mean) could be useful in many contexts

**Describe the solution you'd like**

~~~ julia
using NeutralLandscapes

# this already exists
env = rand(MidpointDisplacement(0.5), 250, 250)

# new stuff
rate = 5
change = Directional(rate, θ = 90)

update!(env, change)
~~~

**Comment by gottacatchenall** [comment]
alternatively the `change` struct could hold a function `f` that updates the value of a cell `x(t) = x(t-1) + f(x(t-1))`

**Comment by tpoisot** [comment]
The hard part would be to maybe specify the amount of spatial and temporal autocorrelation we want?

**Comment by gottacatchenall** [comment]
made a prototype in #57. 

my thinking is we can use `NeutralLandscapeMakers` for spatial autocorrelation and generate a time series with a given expected autocorrelation and weight the mean of the change in each cell at each time by it
