### ISSUE TITLE
HaltonSequences is misbehaving

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/NeutralLandscapes.jl#65]
We (me + @TanyaS08 and @beasley015) have been running into issues with `NeutralLandscapes` using julia 1.9 in different projects, on different OS. I can install the package just fine on its own, but with additional project dependencies, it sometimes chokes because there's an issue with `HaltonSequences` and its `Primes` dependency.

I started the `bug/HaltonSequences1dot9` branch to see what's up, but maybe @gottacatchenall has encountered the same?

**Comment by gottacatchenall** [comment]
~~I'd bet on stale dependency versions, I'll take a look~~

**Comment by tpoisot** [comment]
I'm not sure it's this, because it installs fine in an empty project. I think @Beasley015 got it working in a project with additional dependencies but I'm not sure how.

**Comment by tpoisot** [comment]
I'm not sure it's this, because it installs fine in an empty project. I think @Beasley015 got it working in a project with additional dependencies but I'm not sure how.

**Comment by gottacatchenall** [comment]
Is it SpeciesDistributionToolkit the additional dependency? I vaguely remember running into a problem with HaltonSequence dependencies a month or so back, but I didn't write down what happened so I don't remember how I got around it :upside_down_face:

**Comment by tpoisot** [comment]
Oh we're gonna blame my code then uh?

I don't think it was a dependency in either project, but I think `Makie` was -- I'll make a list of the dependencies in either and see if I can figure out which is the problem.

**Comment by gottacatchenall** [comment]
Don't worry, my lack of writing shit down is the culprit here---clearing out the [compat] on Project.toml might be the quickest way to working code

**Comment by gottacatchenall** [comment]
In an empty project directory with Julia 1.9.3  I was able to `]add SpeciesDistributionToolkit` and `]add BiodiversityObservationNetworks`, and run 

```
using SpeciesDistributionToolkit
using BiodiversityObservationNetworks
```
without issue. 

I'm curious if that is true for everyone in this thread?

**Comment by Beasley015** [comment]
Like @tpoisot said, I managed to get `NeutralLandscapes` working in an empty project using Julia 1.9. I was also able to install it in a project with `DataFrames`, `StatsBase`, `PkgCite`, and `Plots`, so none of those are the issue.

I can test `Makie`, `SpeciesDistributionToolkit`, and `BiodiversityObservationNetworks` this afternoon.

**Comment by gottacatchenall** [comment]
Sounds good, iirc it was something particular to GeoMakie that was causing the issue

**Comment by Beasley015** [comment]
`SpeciesDistributionToolkit` and `BiodiversityObservationNetworks` work with `NeutralLandscapes`. 

I reproduced the error in a project that only had `NeutralLandscapes` and `Makie`- so it seems like `Makie` or one of its dependencies is causing the issue

**Comment by tpoisot** [comment]
I had the issue with `GLMakie` for sure, I can't remember if `CairoMakie` gave the same error...

**Comment by gottacatchenall** [comment]
I'm able to run `add GLMakie, BiodiversityObservationNetworks, SpeciesDistributionToolkit, NeutralLandscapes` and load and use them from an empty project, are there any other packages in the env?

**Comment by mkborregaard** [comment]
Maybe keep in mind that environments are nested - so it could also be an interaction with something in your default env?

**Comment by gottacatchenall** [comment]
In another project I ran into this again, looks like HaltonSequences and StatsBase are constrained by NeutralLandscapes and that's like whats causing problems 

![image](https://github.com/EcoJulia/NeutralLandscapes.jl/assets/17133743/43d2a97f-27de-4906-ba0c-80ebd21ce054)

**Comment by gottacatchenall** [comment]
The bump to `v0.1.4` seems to have fixed this on my end
